apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: my-image
      resources:
        limits:
          cpu: "500m"    # 500 milliCPU (0.5 CPU cores)
          memory: "512Mi"  # 512 Mebibytes (MiB) of memory
        requests:
          cpu: "200m"    # 200 milliCPU (0.2 CPU cores)
          memory: "256Mi"  # 256 Mebibytes (MiB) of memory
